import { motion } from 'framer-motion';
import CountUp from 'react-countup';
import {
  ShieldCheck, CloudSun, Radio, Zap, Compass,
  type LucideIcon,
} from 'lucide-react';
import { GlassCard, SectionHeading } from '@/components/ui/GlassCard';
import { AI_METRICS } from '@/constants/data';

const ICONS: Record<string, LucideIcon> = {
  ShieldCheck, CloudSun, Radio, Zap, Compass,
};

const COLOR_MAP: Record<string, { text: string; bar: string; ring: string }> = {
  green: { text: 'text-neon-green', bar: 'from-neon-green to-neon-cyan', ring: 'border-neon-green/40' },
  cyan: { text: 'text-neon-cyan', bar: 'from-neon-cyan to-neon-blue', ring: 'border-neon-cyan/40' },
  blue: { text: 'text-neon-blue', bar: 'from-neon-blue to-neon-indigo', ring: 'border-neon-blue/40' },
  amber: { text: 'text-neon-amber', bar: 'from-neon-amber to-neon-red', ring: 'border-neon-amber/40' },
  indigo: { text: 'text-neon-indigo', bar: 'from-neon-indigo to-neon-blue', ring: 'border-neon-indigo/40' },
};

const STATUS_LABEL: Record<string, string> = {
  low: 'Low Risk',
  nominal: 'Nominal',
  caution: 'Caution',
};

export function AIAnalytics() {
  return (
    <section id="analytics" className="relative py-24 px-6">
      <div className="mx-auto max-w-7xl">
        <SectionHeading
          eyebrow="Predictive Intelligence"
          title="AI Mission Analytics"
          subtitle="Autonomous assessment of mission-critical subsystems, with recommendations generated by the onboard intelligence layer."
        />

        <div className="mt-14 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {/* Featured AI panel */}
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-60px' }}
            transition={{ duration: 0.7 }}
            className="md:col-span-2 lg:col-span-1 lg:row-span-2"
          >
            <GlassCard hud glow="cyan" className="p-6 h-full flex flex-col">
              <div className="flex items-center gap-2 mb-4">
                <span className="relative flex h-2 w-2">
                  <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-neon-cyan opacity-75" />
                  <span className="relative inline-flex h-2 w-2 rounded-full bg-neon-cyan" />
                </span>
                <span className="font-heading text-sm uppercase tracking-widest text-neon-cyan">AI Core — Active</span>
              </div>

              <h3 className="font-display text-2xl font-bold text-white mb-3">Mission Risk Assessment</h3>

              <div className="relative flex items-center justify-center my-6">
                <svg viewBox="0 0 120 120" className="w-40 h-40">
                  <circle cx="60" cy="60" r="50" fill="none" stroke="#1e293b" strokeWidth="8" />
                  <motion.circle
                    cx="60"
                    cy="60"
                    r="50"
                    fill="none"
                    stroke="#22d3ee"
                    strokeWidth="8"
                    strokeLinecap="round"
                    strokeDasharray={2 * Math.PI * 50}
                    initial={{ strokeDashoffset: 2 * Math.PI * 50 }}
                    whileInView={{ strokeDashoffset: 2 * Math.PI * 50 * (1 - 0.18) }}
                    viewport={{ once: true }}
                    transition={{ duration: 1.8, ease: 'easeOut' }}
                    transform="rotate(-90 60 60)"
                    style={{ filter: 'drop-shadow(0 0 6px #22d3ee)' }}
                  />
                </svg>
                <div className="absolute text-center">
                  <div className="font-display text-4xl font-bold text-neon-green">
                    <CountUp end={18} duration={2} suffix="%" />
                  </div>
                  <div className="font-heading text-[10px] uppercase tracking-widest text-slate-400">Risk Score</div>
                </div>
              </div>

              <div className="mt-auto glass rounded-lg p-4">
                <div className="font-heading text-[10px] uppercase tracking-widest text-neon-cyan mb-1">Recommendation</div>
                <p className="font-body text-sm text-slate-300 leading-relaxed">
                  All subsystems within nominal parameters. No corrective action required for current orbital pass.
                </p>
              </div>
            </GlassCard>
          </motion.div>

          {/* Metric cards */}
          {AI_METRICS.slice(1).map((metric, idx) => {
            const Icon = ICONS[metric.icon];
            const colors = COLOR_MAP[metric.color];
            return (
              <motion.div
                key={metric.id}
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: '-60px' }}
                transition={{ delay: idx * 0.12, duration: 0.7 }}
              >
                <GlassCard hud className={`p-6 h-full border ${colors.ring}`}>
                  <div className="flex items-start justify-between mb-4">
                    <div className={`flex h-10 w-10 items-center justify-center rounded-xl bg-white/5 ${colors.text}`}>
                      <Icon className="w-5 h-5" />
                    </div>
                    <span className={`font-heading text-[10px] uppercase tracking-widest ${colors.text}`}>
                      {STATUS_LABEL[metric.status]}
                    </span>
                  </div>

                  <div className="font-heading text-xs uppercase tracking-widest text-slate-400 mb-1">{metric.title}</div>
                  <div className={`font-display text-3xl font-bold ${colors.text}`}>
                    <CountUp end={metric.value} duration={2} suffix={metric.suffix} />
                  </div>

                  <div className="mt-3 h-1.5 w-full rounded-full bg-white/10 overflow-hidden">
                    <motion.div
                      className={`h-full rounded-full bg-gradient-to-r ${colors.bar}`}
                      initial={{ width: 0 }}
                      whileInView={{ width: `${metric.value}%` }}
                      viewport={{ once: true }}
                      transition={{ duration: 1.4, ease: 'easeOut' }}
                    />
                  </div>

                  <p className="mt-4 font-body text-xs text-slate-400 leading-relaxed">{metric.recommendation}</p>
                </GlassCard>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
